export const AnnouncementModel = {
  sell_type_id: "",
  asset_type_id: "",
  title: "",
  project_name: "",
  address: "",
  street: "",
  soi: "",
  province_id: "",
  district_id: "",
  sub_district_id: "",
  postal_code: "",
  google_map_location: "",
  bedroom_count: "",
  bathroom_count: "",
  floor_level: "",
  square_meter: "",
  price: "",
  description: "",
  images: [] as File[],
  old_images: [],
};
